# https://docs.travis-ci.com/user/docker/
# https://docs.travis-ci.com/user/environment-variables/
# https://docs.travis-ci.com/user/job-lifecycle/

# You can import up to 25 other configs in total.
os: linux

before_script:
  - sudo apt update
  - sudo apt install -y python3 python3-pip python3-dev python3-wheel python3-setuptools
  - python3 -m pip install pipenv

jobs:
  include:

    - stage: Merge
      script:
        - wget https://raw.githubusercontent.com/louiscklaw/travis-playlist/master/travis-build-merger/merge_if_success.sh
        - bash merge_if_success.sh

    - stage: Test
      name: unittest-helloworld
      script:
        - cd unittest-helloworld
        - pipenv sync
        - pipenv run python3 main.py
        - cd ..


stages:
  - Unit_test
  - Test
  - Build
  - Deploy
  - Integration_to_other_repo
  - Publish_dashboard
  - Merge

import:
  - credentials.yml
