# https://docs.travis-ci.com/user/docker/
# https://docs.travis-ci.com/user/environment-variables/
# https://docs.travis-ci.com/user/job-lifecycle/

# You can import up to 25 other configs in total.
os: linux

language: node_js

node_js:
  - 12

cache:
  - npm
  - pip

jobs:
  include:
    - stage: Unit_Test
      name: unittest-helloworld

      before_script:
        - sudo apt update
        - sudo apt install -y python3 python3-pip python3-dev python3-wheel python3-setuptools
        - python3 -m pip install pipenv

      script:
        - cd unittest-helloworld
        - pipenv sync
        - pipenv run python3 main.py
        - cd ..

    - stage: Unit_Test
      name: unittest-xmlrunner-tryout

      before_script:
        - sudo apt update
        - sudo apt install -y python3 python3-pip python3-dev python3-wheel python3-setuptools
        - python3 -m pip install pipenv

      script:
        - cd unittest-xmlrunner-tryout
        - mkdir -p test-reports
        - pipenv sync
        - pipenv run python3 test/unit/test_unit.py
        - pipenv run python3 test/integration/test_integration.py
        - pipenv run python3 test/system/test_system.py
        - pipenv run python3 test/sanity/test_sanity.py
        - pipenv run python3 test/smoke/test_smoke.py
        - pipenv run python3 test/interface/test_interface.py
        - pipenv run python3 test/regression/test_regression.py
        - pipenv run python3 test/acceptance/test_acceptance.py

        - cd ..

    - stage: Unit_Test
      name: test unittest-html-test-runner-helloworld

      before_script:
        - sudo apt update
        - sudo apt install -y python3 python3-pip python3-dev python3-wheel python3-setuptools
        - python3 -m pip install pipenv

      script:
        - cd unittest-html-test-runner-helloworld
        - pipenv sync
        - pipenv run python3 main.py || true
        - cd ..

    - stage: Unit_Test
      name: test (unittest-json-reporting-tryout)

      env:
        _ WKDIR=$HOME/unittest-json-reporting-tryout/src
        - SRC_DIR=$WKDIR
        - PROJ_HOME=$WKDIR/..
        - REPORT_DIR=$WKDIR/test-reports


      before_script:
        - sudo apt update
        - sudo apt install -y python3 python3-pip python3-dev python3-wheel python3-setuptools
        - python3 -m pip install pipenv

      script:
        - cd unittest-json-reporting-tryout/src

        - mkdir -p $REPORT_DIR
        - pipenv sync
        - pipenv run python3 before_test.py
        # accept failed test case as demo case
        - pipenv run python3 test/unit/test_unit_run.py
        - pipenv run python3 test/integration/test_integration_run.py
        - pipenv run python3 test/sanity/test_sanity_run.py
        - pipenv run python3 test/smoke/test_smoke_run.py
        - pipenv run python3 test/interface/test_interface_run.py
        - pipenv run python3 test/regression/test_regression_run.py
        - pipenv run python3 test/acceptance/test_acceptance_run.py

        - pipenv run python3 after_test.py
        - pipenv run python3 ./attach_docstring.py
        - pipenv run python3 ./attach_testsuite_docstring.py
        - pipenv run python3 ./attach_reports_meta.py

        - cd ../..

    - stage: Publish_Result
      name: generate gatsby test result page (by gatsby-test-result-page)

      before_script:
        - cd unittest-json-reporting-tryout/src

        - mkdir -p $REPORT_DIR
        - pipenv sync
        - pipenv run python3 before_test.py
        # accept failed test case as demo case
        - pipenv run python3 test/unit/test_unit_run.py
        - pipenv run python3 test/integration/test_integration_run.py
        - pipenv run python3 test/sanity/test_sanity_run.py
        - pipenv run python3 test/smoke/test_smoke_run.py
        - pipenv run python3 test/interface/test_interface_run.py
        - pipenv run python3 test/regression/test_regression_run.py
        - pipenv run python3 test/acceptance/test_acceptance_run.py

        - pipenv run python3 after_test.py
        - pipenv run python3 ./attach_docstring.py
        - pipenv run python3 ./attach_testsuite_docstring.py
        - pipenv run python3 ./attach_reports_meta.py

        - cd ../..

      script:
        - cd gatsby-test-result-page

        # copy result json files from (unittest-json-reporting-tryout)
        - ./regen_test_result.sh

        - yarn
        - yarn build

        - cd ..

      deploy:
        - provider: pages
          skip_cleanup: true
          local_dir: gh-pages
          github_token: $GITHUB_TOKEN


    - stage: Merge
      script:
        - wget https://raw.githubusercontent.com/louiscklaw/travis-playlist/master/travis-build-merger/merge_if_success.sh
        - bash merge_if_success.sh

    - stage: Publish_Result
      name: test publish result

      before_script:
        - sudo apt update
        - sudo apt install -y python3 python3-pip python3-dev python3-wheel python3-setuptools
        - python3 -m pip install pipenv

      script:
        - cd unittest-html-test-runner-helloworld
        -   pipenv sync
        -   pipenv run python3 main.py || true
        - cd ..

      deploy:
        - provider: pages
          skip_cleanup: true
          local_dir: unittest-html-test-runner-helloworld/reports
          github_token: $GITHUB_TOKEN
          on:
            branch: master

      if: branch = master

      after_failure:
        - node -v
        - ls -l unittest-html-test-runner-helloworld/reports
        - cat /home/travis/.npm/_logs/*.log

stages:
  - Unit_test
  - Test
  - Build
  - Deploy
  - Integration_to_other_repo
  - Publish_dashboard
  - Merge
  - Publish_Result

import:
  - credentials.yml
