
jobs:
  include:
    - stage: Unit_Test
      name: test (helloworld-tryout)

      before_script:
        - sudo apt update
        - sudo apt install -y python3 python3-pip python3-dev python3-wheel python3-setuptools
        - python3 -m pip install pipenv

      script:
        - cd helloworld-tryout
        - pipenv sync
        - pipenv run python3 main.py
        - cd ..
