
#
# /home/logic/_workspace/python-playlist/github-build-merger/subjob.yml
#
helloworld-tryout:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2

    - run: |
      cd helloworld-tryout
        pipenv sync
        pipenv run python3 ./main.py

    env: # Or as an environment variable
      SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
