
jobs:
  include:
    - stage: Unit_Test
      name: test (pytest-helloworld)

      before_script:
        - sudo apt update
        - sudo apt install -y python3 python3-pip python3-dev python3-wheel python3-setuptools
        - python3 -m pip install pipenv

      script:
        - cd pytest-helloworld
        - pipenv sync
        - pipenv run pytest
        - cd ..
