name: master_build
on: [push]

jobs:

  #
  # /home/logic/_workspace/github-playlist/helloworld-tryout/build.yml
  #
  # https://docs.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets
  helloworld-tryout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: helloworld-tryout
        run:
          hostname